services:
  # Web service that serves the Flask health check API
  - type: web
    name: tts-bot-web
    env: python
    buildCommand: pip install -e .
    startCommand: gunicorn --bind 0.0.0.0:$PORT main:app
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: TELEGRAM_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: tts-bot-db
          property: connectionString

  # Background worker that runs the Telegram bot
  - type: worker
    name: tts-bot-worker
    env: python
    buildCommand: pip install -e .
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: TELEGRAM_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: tts-bot-db
          property: connectionString

databases:
  - name: tts-bot-db
    plan: free